### ISSUE TITLE
Rebase to alpine

### ISSUE THREAD

**Issue by rix1337** [rix1337/docker-rsscrawler#5]
Use smaller baseimage.

No deadline.

**Comment by Gutz-Pilz** [comment]
vielleicht auch 
`phusion/baseimage:0.9.18`

**Comment by rix1337** [comment]
Das zerschießt das Setup, weil es auf xenial basiert

**Comment by Gutz-Pilz** [comment]
`FROM python:2-alpine `

**Comment by rix1337** [comment]
Probieren ich gerne aus. Die phusion Releases sind auch nervig geworden.. xenial hat so einiges verändert.

Ich schau mir das mal die tage an!

**Comment by rix1337** [comment]
Die Paketverwaltung und auch die DIenste laufen in alpine anders.

Ich werd mir das die Tage ansehen..

**Comment by rix1337** [comment]
https://hub.docker.com/r/rix1337/alpine-rsscrawler/builds/

erste Ergebnisse. Läuft noch nicht rund. Sobald das funktioniert, update ich diese version!
